[package]
name = "igorrrbot-poise"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
regex = "1.11.2"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.13"
